# Generated by Django 3.2.16 on 2022-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stolovaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=255, verbose_name='Группа')),
                ('fio', models.CharField(max_length=255, verbose_name='fio')),
                ('typeofeda', models.CharField(choices=[('normal', 'normal'), ('lgota14', 'lgota14'), ('lgota59', 'lgota59'), ('internat14', 'internat14'), ('internat59', 'internat'), ('kompleks', 'kompleks')], default='normal', max_length=255, verbose_name='typeofeda')),
            ],
            options={
                'verbose_name': 'Stolovaya',
                'verbose_name_plural': 'Stolovaya',
                'ordering': ['classname', 'fio'],
            },
        ),
        migrations.CreateModel(
            name='stolovayainfodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapit', models.DateField(verbose_name='datapitaniya')),
                ('uchid', models.IntegerField(verbose_name='id_uchenika')),
                ('chkflag', models.BooleanField(verbose_name='checked')),
                ('datazapis', models.DateTimeField(blank=True, verbose_name='datazapis')),
            ],
        ),
        migrations.AddField(
            model_name='stolovaya',
            name='internat',
            field=models.CharField(choices=[('2-level', '2-level'), ('3-level', '3-level'), ('4-level', '3-level')], default='2-level', max_length=255, verbose_name='internat'),
        ),

    ]
