# Generated by Django 3.2.16 on 2022-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0004_auto_20221206_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolovaya',
            name='typeofeda',
            field=models.CharField(choices=[('normal', 'normal'), ('lgota14', 'lgota14'), ('lgota59', 'lgota59'), ('internat14', 'internat14'), ('internat59', 'internat59'), ('kompleks', 'kompleks')], default='normal', max_length=255, verbose_name='typeofeda'),
        ),
    ]
