# Generated by Django 3.2.16 on 2022-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0005_alter_stolovaya_typeofeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolovaya',
            name='medflag',
            field=models.BooleanField(default=False, verbose_name='medcenter'),
        ),
    ]
