# Generated by Django 3.2.16 on 2022-12-13 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0007_alter_stolovaya_internat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stolovayainfopit',
            options={'get_latest_by': 'datapittime'},
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='datapittime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='datazapis'),
            preserve_default=False,
        ),
    ]
