# Generated by Django 3.2.16 on 2022-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0009_stolovayainfopit_forceflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='stolovayapodacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zavtrak', models.TimeField(verbose_name='zavtrak')),
                ('obed', models.TimeField(verbose_name='obed')),
                ('poldnik', models.TimeField(verbose_name='poldnik')),
                ('ujin1', models.TimeField(verbose_name='ujin1')),
                ('ujin2', models.TimeField(verbose_name='ujin2')),
            ],
        ),
    ]
