# Generated by Django 3.2.16 on 2022-12-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('stolovaya', '0010_stolovayapodacha'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolovayapodacha',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
