# Generated by Django 3.2.16 on 2022-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0011_stolovayapodacha_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolovayainfopit',
            name='forceflag',
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflago',
            field=models.DateTimeField(default=None, verbose_name='force_checked_o'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagp',
            field=models.DateTimeField(default=None, verbose_name='force_checked_p'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagu1',
            field=models.DateTimeField(default=None, verbose_name='force_checked_u1'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagu2',
            field=models.DateTimeField(default=None, verbose_name='force_checked_u2'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagz',
            field=models.DateTimeField(default=None, verbose_name='force_checked_z'),
        ),
    ]
