# Generated by Django 3.2.16 on 2022-12-15 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0012_auto_20221214_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='stolovayainfopitmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapit', models.DateField(verbose_name='datapitaniya')),
                ('zavtrak', models.BooleanField(verbose_name='z_checked')),
                ('obed', models.BooleanField(verbose_name='o_checked')),
                ('poldnik', models.BooleanField(verbose_name='p_checked')),
                ('ujin1', models.BooleanField(verbose_name='u1_checked')),
                ('ujin2', models.BooleanField(verbose_name='u2_checked')),
                ('datapittime', models.DateTimeField(blank=True, verbose_name='datazapis')),
                ('forceflagz', models.DateTimeField(default=None, verbose_name='force_checked_z')),
                ('forceflago', models.DateTimeField(default=None, verbose_name='force_checked_o')),
                ('forceflagp', models.DateTimeField(default=None, verbose_name='force_checked_p')),
                ('forceflagu1', models.DateTimeField(default=None, verbose_name='force_checked_u1')),
                ('forceflagu2', models.DateTimeField(default=None, verbose_name='force_checked_u2')),
                ('uchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stolovaya.stolovaya', verbose_name='id_uchenika')),
            ],
            options={
                'get_latest_by': 'datapittime',
            },
        ),
    ]
