# Generated by Django 3.2.16 on 2022-12-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0013_stolovayainfopitmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='stolovayainfodatamed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapit', models.DateField(verbose_name='datapitaniya')),
                ('chkflag', models.BooleanField(verbose_name='checked')),
                ('datazapis', models.DateTimeField(blank=True, verbose_name='datazapis')),
                ('uchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stolovaya.stolovaya', verbose_name='id_uchenika')),
            ],
        ),
    ]
