# Generated by Django 3.2.16 on 2022-12-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0014_stolovayainfodatamed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolovayainfopitmed',
            name='uchid',
        ),
        migrations.DeleteModel(
            name='stolovayainfodatamed',
        ),
        migrations.DeleteModel(
            name='stolovayainfopitmed',
        ),
    ]
