# Generated by Django 3.2.16 on 2022-12-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0017_auto_20221215_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='forceflago',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_o'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='forceflagp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_p'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='forceflagu1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_u1'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='forceflagu2',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_u2'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='forceflagz',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_z'),
        ),
    ]
