# Generated by Django 3.2.16 on 2022-12-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0018_auto_20221215_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='stolovayatalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime1', models.DateTimeField(verbose_name='DateTime_otmetka')),
                ('dateeda', models.DateTimeField(verbose_name='Date_pitania')),
                ('catoftalon', models.CharField(choices=[('obed1', 'obed2'), ('obed2', 'obed2')], default='obed1', max_length=255, verbose_name='catoftalon')),
            ],
        ),
    ]
