# Generated by Django 3.2.16 on 2022-12-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0019_stolovayatalon'),
    ]

    operations = [
        migrations.CreateModel(
            name='stolovayacategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime1', models.DateTimeField(verbose_name='DateTime_otmetka')),
                ('dateeda', models.DateTimeField(verbose_name='Date_pitania')),
                ('category', models.CharField(choices=[('normal', 'normal'), ('lgota14', 'lgota14'), ('lgota59', 'lgota59'), ('internat14', 'internat14'), ('internat59', 'internat59'), ('kompleks', 'kompleks')], default='normal', max_length=255, verbose_name='typeofeda')),
                ('uchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stolovaya.stolovaya', verbose_name='id_uchenika')),
            ],
        ),
    ]
