# Generated by Django 3.2.16 on 2022-12-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0021_auto_20221219_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolovaya',
            name='typeofeda',
        ),
        migrations.AddField(
            model_name='stolovayatalon',
            name='numoftalons',
            field=models.IntegerField(default=0, verbose_name='numoftalons'),
            preserve_default=False,
        ),
    ]
