# Generated by Django 3.2.16 on 2022-12-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0022_auto_20221219_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagmed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_med'),
        ),
    ]
