# Generated by Django 3.2.16 on 2022-12-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('stolovaya', '0023_stolovayainfopit_forceflagmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolovaya',
            name='internat',
            field=models.CharField(choices=[('normal', 'Обычные'), ('2-level', '2-level'), ('3-level', '3-level'), ('4-level', '4-level')], default='normal', max_length=255, verbose_name='internat'),
        ),
        migrations.AlterField(
            model_name='stolovayacategory',
            name='category',
            field=models.CharField(choices=[('normal', 'Обычные'), ('lgota14', 'Льготники младшие'), ('lgota59', 'Льготники старшие'), ('internat14', 'Интернат младшие'), ('internat59', 'Интернат старшие'), ('kompleks', 'Комплексный Обед')], default='normal', max_length=255, verbose_name='typeofeda'),
        ),
        migrations.AlterField(
            model_name='stolovayapodacha',
            name='obed',
            field=models.TimeField(verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='stolovayapodacha',
            name='poldnik',
            field=models.TimeField(verbose_name='Полдник'),
        ),
        migrations.AlterField(
            model_name='stolovayapodacha',
            name='ujin1',
            field=models.TimeField(verbose_name='Ужин 1'),
        ),
        migrations.AlterField(
            model_name='stolovayapodacha',
            name='ujin2',
            field=models.TimeField(verbose_name='Ужин 2'),
        ),
        migrations.AlterField(
            model_name='stolovayapodacha',
            name='zavtrak',
            field=models.TimeField(verbose_name='Завтрак'),
        ),
        migrations.CreateModel(
            name='stolovayapriemipishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zavtrak', models.TimeField(verbose_name='Завтрак')),
                ('obed', models.TimeField(verbose_name='Обед')),
                ('poldnik', models.TimeField(verbose_name='Полдник')),
                ('ujin1', models.TimeField(verbose_name='Ужин 1')),
                ('ujin2', models.TimeField(verbose_name='Ужин 2')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
