# Generated by Django 3.2.16 on 2022-12-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0024_auto_20221221_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolovaya',
            name='medflag',
        ),
        migrations.CreateModel(
            name='stolovayamedflag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime1', models.DateTimeField(verbose_name='DateTime_otmetka')),
                ('dateeda', models.DateField(verbose_name='Date_pitania')),
                ('medflag', models.BooleanField(default=False, verbose_name='medcenter')),
                ('uchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stolovaya.stolovaya', verbose_name='id_uchenika')),
            ],
        ),
    ]
