# Generated by Django 3.2.16 on 2022-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0025_auto_20221221_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagok',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_ok'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='obedk',
            field=models.BooleanField(blank=True, null=True, verbose_name='kompleks_checked'),
        ),
        migrations.AddField(
            model_name='stolovayapodacha',
            name='obedk',
            field=models.TimeField(blank=True, null=True, verbose_name='Комплексный Обед'),
        ),
        migrations.AddField(
            model_name='stolovayapriemipishi',
            name='obedk',
            field=models.TimeField(blank=True, null=True, verbose_name='Комплексный Обед'),
        ),
    ]
