# Generated by Django 3.2.16 on 2022-12-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0027_stolovayainfopit_forceafter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolovayainfopit',
            name='forceafter',
        ),
        migrations.CreateModel(
            name='stolovayainfopitafter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapit', models.DateField(verbose_name='datapitaniya')),
                ('zavtrak', models.BooleanField(verbose_name='z_checked')),
                ('obed', models.BooleanField(verbose_name='o_checked')),
                ('poldnik', models.BooleanField(verbose_name='p_checked')),
                ('ujin1', models.BooleanField(verbose_name='u1_checked')),
                ('ujin2', models.BooleanField(verbose_name='u2_checked')),
                ('obedk', models.BooleanField(blank=True, null=True, verbose_name='kompleks_checked')),
                ('datapittime', models.DateTimeField(blank=True, verbose_name='datazapis')),
                ('uchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stolovaya.stolovaya', verbose_name='id_uchenika')),
            ],
        ),
    ]
