# Generated by Django 3.2.16 on 2022-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0028_auto_20221221_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='obed',
            field=models.BooleanField(blank=True, null=True, verbose_name='o_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='poldnik',
            field=models.BooleanField(blank=True, null=True, verbose_name='p_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='ujin1',
            field=models.BooleanField(blank=True, null=True, verbose_name='u1_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='ujin2',
            field=models.BooleanField(blank=True, null=True, verbose_name='u2_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopit',
            name='zavtrak',
            field=models.BooleanField(blank=True, null=True, verbose_name='z_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopitafter',
            name='obed',
            field=models.BooleanField(blank=True, null=True, verbose_name='o_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopitafter',
            name='poldnik',
            field=models.BooleanField(blank=True, null=True, verbose_name='p_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopitafter',
            name='ujin1',
            field=models.BooleanField(blank=True, null=True, verbose_name='u1_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopitafter',
            name='ujin2',
            field=models.BooleanField(blank=True, null=True, verbose_name='u2_checked'),
        ),
        migrations.AlterField(
            model_name='stolovayainfopitafter',
            name='zavtrak',
            field=models.BooleanField(blank=True, null=True, verbose_name='z_checked'),
        ),
    ]
