# Generated by Django 3.2.16 on 2022-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0029_auto_20221226_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stolovaya',
            name='internat',
            field=models.CharField(choices=[('normal', 'Обычные'), ('2-level', '2-Этаж'), ('3-level', '3-Этаж'), ('4-level', '4-Этаж')], default='normal', max_length=255, verbose_name='internat'),
        ),
    ]
