# Generated by Django 3.2.16 on 2022-12-28 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0030_alter_stolovaya_internat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolovaya',
            name='pitenflag',
        ),
        migrations.AddField(
            model_name='stolovaya',
            name='pitendateen',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 1, 1, 1, 1), verbose_name='Pitanie_po_menu_s'),
        ),
    ]
