# Generated by Django 3.2.16 on 2022-12-29 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0032_alter_stolovaya_pitendateen'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolovaya',
            name='pitendatedi',
            field=models.DateField(default=datetime.datetime(2030, 1, 1, 1, 1, 1, 1), verbose_name='Pitanie_po_menu_s'),
        ),
        migrations.AlterField(
            model_name='stolovaya',
            name='pitendateen',
            field=models.DateField(default=datetime.datetime(2001, 1, 1, 1, 1, 1, 1), verbose_name='Pitanie_po_menu_s'),
        ),
    ]
