# Generated by Django 3.2.16 on 2023-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0034_alter_stolovaya_pitendateen'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagod1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_od1'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagod2',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_od2'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='obedkg1',
            field=models.BooleanField(blank=True, null=True, verbose_name='dogovor_1_checked'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='obedkg2',
            field=models.BooleanField(blank=True, null=True, verbose_name='dogovor_2_checked'),
        ),
        migrations.AddField(
            model_name='stolovayainfopitafter',
            name='obedkg1',
            field=models.BooleanField(blank=True, null=True, verbose_name='obedkg1_checked'),
        ),
        migrations.AddField(
            model_name='stolovayainfopitafter',
            name='obedkg2',
            field=models.BooleanField(blank=True, null=True, verbose_name='obedkg2_checked'),
        ),
        migrations.AddField(
            model_name='stolovayapodacha',
            name='obedkg1',
            field=models.TimeField(blank=True, null=True, verbose_name='obedkg1'),
        ),
        migrations.AddField(
            model_name='stolovayapodacha',
            name='obedkg2',
            field=models.TimeField(blank=True, null=True, verbose_name='obedkg2'),
        ),
        migrations.AddField(
            model_name='stolovayapriemipishi',
            name='obedkg1',
            field=models.TimeField(blank=True, null=True, verbose_name='obedkg1'),
        ),
        migrations.AddField(
            model_name='stolovayapriemipishi',
            name='obedkg2',
            field=models.TimeField(blank=True, null=True, verbose_name='obedkg2'),
        ),
        migrations.AlterField(
            model_name='stolovayacategory',
            name='category',
            field=models.CharField(choices=[('normal', 'Обычные'), ('lgota14', 'Льготники младшие'), ('lgota59', 'Льготники старшие'), ('internat14', 'Интернат младшие'), ('internat59', 'Интернат старшие'), ('dogovor1', 'dogovor1'), ('dogovor2', 'dogovor2')], default='normal', max_length=255, verbose_name='typeofeda'),
        ),
    ]
