# Generated by Django 3.2.16 on 2023-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0035_auto_20230106_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolovayainfopit',
            name='forceflagod1',
        ),
        migrations.RemoveField(
            model_name='stolovayainfopit',
            name='forceflagod2',
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagokg1',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_okg1'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagokg2',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_okg2'),
        ),
    ]
