# Generated by Django 3.2.16 on 2023-01-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0038_auto_20230111_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolovayainfopit',
            name='forceflagozg',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='force_checked_ozg'),
        ),
        migrations.AddField(
            model_name='stolovayainfopit',
            name='zavtrakg',
            field=models.BooleanField(blank=True, null=True, verbose_name='zavtrak_g_checked'),
        ),
        migrations.AddField(
            model_name='stolovayainfopitafter',
            name='zavtrakg',
            field=models.BooleanField(blank=True, null=True, verbose_name='zavtrakg_checked'),
        ),
        migrations.AddField(
            model_name='stolovayapodacha',
            name='zavtrakg',
            field=models.TimeField(blank=True, null=True, verbose_name='zavtrakg'),
        ),
        migrations.AddField(
            model_name='stolovayapriemipishi',
            name='zavtrakg',
            field=models.TimeField(blank=True, null=True, verbose_name='zavtrakg'),
        ),
    ]
