# Generated by Django 3.2.16 on 2023-03-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stolovaya', '0041_stolovayafactstol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolovayacategory',
            name='xvarx',
            field=models.IntegerField(default=1, verbose_name='multiplier'),
        ),
    ]
