BBBB BBBBBBBB BBBBBBBBBBBB
XXXXXX
    XXXXXX
        XXXXXXXBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXX
        XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBBBB BBBBB
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXXXX
         #

        BBBBB BBBBBBBBBBBBBB
        BBBBB BBBBBBB
            BBBBBBBBBBB BBBBBBBBB
        BBBBBBBB
        BBBBB BBBBBBBBBBBB
        BBBBB BBBBBBBBBBBBBBBB
        BBBBBBBBBBBB BBBB
        BBBBBBBBBBBB BBBBBBBB

    XXXXXXX
XXXXXXX
