# Generated by Django 3.2.16 on 2022-11-18 16:21

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='filebrowserplugin_fileplugin', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('link', filebrowser.fields.FileBrowseField(max_length=255, verbose_name='link')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
