# Generated by Django 3.2.16 on 2022-11-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebrowserplugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileplugin',
            name='showsize',
            field=models.BooleanField(default=True, verbose_name='showsize'),
        ),
    ]
