# Generated by Django 3.2.16 on 2022-11-21 09:05

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filebrowserplugin', '0003_delete_fileplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePlugin',
            fields=[
                ('template', models.CharField(choices=[('default', 'По умолчанию')], default='default', max_length=255, verbose_name='Шаблон')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('link', filebrowser.fields.FileBrowseField(max_length=255, verbose_name='link')),
                ('link_target', models.CharField(blank=True, choices=[('_self', 'Открыть в том же окне'), ('_blank', 'Открыть в новом окне'), ('_parent', 'Передать в родительский фрейм'), ('_top', 'Передать в окно верхнего уровня')], default='', max_length=255, verbose_name='Link target')),
                ('showsize', models.BooleanField(default=True, verbose_name='showsize')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Атрибуты')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='filebrowserplugin_fileplugin', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
