# Generated by Django 3.2.16 on 2022-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebrowserplugin', '0004_fileplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileplugin',
            name='link_target',
            field=models.CharField(blank=True, choices=[('_self', 'Открыть в том же окне'), ('_blank', 'Открыть в новом окне'), ('_parent', 'Передать в родительский фрейм'), ('_top', 'Передать в окно верхнего уровня')], default='_blank', max_length=255, verbose_name='Link target'),
        ),
        migrations.AlterField(
            model_name='fileplugin',
            name='template',
            field=models.CharField(choices=[('default', 'По умолчанию'), ('default', 'default')], default='default', max_length=255, verbose_name='Шаблон'),
        ),
    ]
