# Generated by Django 3.2.16 on 2022-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebrowserplugin', '0005_auto_20221121_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileplugin',
            name='template',
            field=models.CharField(choices=[('default', 'По умолчанию')], default='default', max_length=255, verbose_name='Шаблон'),
        ),
    ]
